CREATE TABLE `inversion` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `inv_tipo` tinyint(3) DEFAULT NULL,
  `inv_fecha_compra` date NOT NULL,
  `inv_propietario` varchar(45) NOT NULL,
  `inv_liquidacion` varchar(15) DEFAULT NULL,
  `inv_instrumento` varchar(60) DEFAULT NULL,
  `inv_fecha_emision` date DEFAULT NULL,
  `inv_fecha_vencimiento` date DEFAULT NULL,
  `inv_fecha_venta` date DEFAULT NULL,
  `inv_emisor` varchar(45) NOT NULL,
  `inv_calificacion_riesgo` varchar(6) DEFAULT NULL,
  `inv_valor_nominal` decimal(8,2) DEFAULT NULL,
  `inv_monto_a_negociar` decimal(8,2) DEFAULT NULL,
  `inv_capital_invertido` decimal(8,2) NOT NULL,
  `inv_tasa_interes` decimal(8,2) NOT NULL,
  `inv_rendimiento_nominal` decimal(8,2) NOT NULL,
  `inv_rendimiento_efectivo` decimal(10,8) DEFAULT NULL,
  `inv_valor_efectivo` decimal(8,2) DEFAULT NULL,
  `inv_valor_interes` decimal(8,2) DEFAULT NULL,
  `inv_comision_bolsa` decimal(8,2) DEFAULT NULL,
  `inv_comision_operador` decimal(8,2) DEFAULT NULL,
  `inv_retencion` decimal(8,2) DEFAULT NULL,
  `inv_expirado` tinyint(1) DEFAULT 0,
  `inv_pagada` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 si la inversion se ha vencido y ha sido pagada / 0 si la inversion todavia no se ha vencido ni ha sido vendida',
  `inv_tasa_mensual_real` decimal(8,2) DEFAULT NULL,
  `inv_interes_primer_mes` decimal(8,2) DEFAULT NULL,
  `inv_fecha_primer_pago` date DEFAULT NULL,
  `inv_precio_comprado` double DEFAULT NULL,
  `inv_precio_neto_comprado` double DEFAULT NULL,
  `inv_valor_sin_comision` decimal(8,2) DEFAULT NULL,
  `inv_valor_con_interes` decimal(8,2) DEFAULT NULL,
  `inv_interes_acumulado_previo` decimal(8,2) DEFAULT NULL,
  `inv_total_comisiones` decimal(8,2) DEFAULT NULL,
  `inv_codigo_SEB` varchar(5) DEFAULT NULL COMMENT 'Codigo específico de bonos',
  `inv_codigo_BCE` varchar(100) DEFAULT NULL COMMENT 'Codigo específico de bonos asignado por el Banco Central',
  `inv_fechas_pagos_capital` varchar(60) DEFAULT NULL,
  `id_instrumento` int(11) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1 COMMENT '1 si la inversion no ha sido vendida / 0 si la inversion ha sido vendida',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '1 si el registro ha sido borrado / 0 si el registro no ha sido borrado',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=432 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci COMMENT='Es una de las tablas más importantes. Contiene el listado de inversiones del portafolio del usuario.';


CREATE TABLE `amortizacion` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `inv_id` int(11) NOT NULL,
  `am_fecha_pago` date NOT NULL,
  `am_interes` decimal(8,2) NOT NULL,
  `am_capital` decimal(8,2) DEFAULT 0.00,
  `am_descuento` decimal(8,2) DEFAULT 0.00,
  `am_int_parcial` decimal(8,2) DEFAULT NULL,
  `am_total` decimal(8,2) DEFAULT 0.00,
  `am_retencion` decimal(8,2) DEFAULT 0.00,
  `am_pagada` tinyint(1) DEFAULT 0 COMMENT '1: la amortizacion ha sido pagada en la fecha / 0: la amortizacion no ha sido pagada porque todavia no llega la fecha/ 2: La amortización esta morosa',
  `is_active` tinyint(1) DEFAULT 1 COMMENT '1: la amortizacion ha sido cobrada o se va a cobrar en algun momento / 0:  la inversion ha sido vendida y la amortizacion no se va a cobrar',
  `is_deleted` tinyint(1) DEFAULT 0 COMMENT '0 si no ha sido borrado / 1 si ha sido borrado ',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=11644 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci COMMENT='Tabla de Amortizacion';
